spring:
  application:
    name: eshop-web
  redis:
    host: 
    port: 6379
    #password:
server:
  port: 8033
  context-path: /
  tomcat:
    uri-encoding: UTF-8
myapp:
   restserviceurl:
     account: http://auth-web:8034
     cart: http://cart-web:8035
     product: http://product-web:8036
   
logging:
  config: classpath:log4j2.xml
