apiVersion: v1
kind: Service
metadata:
  name: auth-web
  labels:
    app: auth-web
spec:
  ports:
    - port: 8034
  selector:
    app: auth-web
    tier: frontend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth-web
  labels:
    app: auth-web
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-web
        tier: frontend
    spec:
      containers:
      - image: auth:v1
        name: auth
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: web-mysql
              key: password.txt
        - name: DB_HOST
          value: web-mysql
        - name: DB_USER
          value: root
        ports:
        - containerPort: 8034
