apiVersion: v1
kind: Service
metadata:
  name: eshop-web
  labels:
    app: eshop-web
spec:
  ports:
    - port: 8033
      nodePort: 30080
  selector:
    app: eshop-web
    tier: frontend
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eshop-web
  labels:
    app: eshop-web
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eshop-web
        tier: frontend
    spec:
      containers:
      - image: eshop:v1
        name: eshop
        env:
        - name: REDIS_HOST
          value: session-redis
        - name: REDIS_PORT
          value: "6379"
        - name: ACCOUNT_URL
          value: "http://auth-web:8034"
        - name: CART_URL
          value: "http://cart-web:8035"
        - name: PRODUCT_URL
          value: "http://product-web:8036"
        ports:
        - containerPort: 8033
