GapiVersion: v1
kind: Service
metadata:
  name: session-redis
  labels:
    app: redis-app
spec:
  ports:
    - port: 6379
  selector:
    app: redis-app
    tier: redis
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: session-redis
  labels: 
    app: redis-app
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis-app
        tier: redis
    spec: 
      containers: 
      - image: redis
        imagePullPolicy: IfNotPresent
        name: reids

